spring:

server:
  port: ${PORT:9090}
  servlet:
    context-path: /employee-service
  connection-timeout: 0

  application:
    name: crudAPI

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:EMPLOYEEDB
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console



